export const angkatan16 = [
  `\n1. Ade.W`,
  `2. Adhin`,
  `3. A.Faqih`,
  `4. Aldimas`,
  `5. Amrul`,
  `6. Andaru`,
  `7. Arga`,
  `8. Arifudin`,
  `9. Bayu`,
  `10. David`,
  `11. Dzilli`,
  `12. Edward  `,
  `13. EL`,
  `14. Faiz`,
  `15. Faqih.D`,
  `16. Farhan`,
  `17. Fikri.Dz`,
  `18. Haekal`,
  `19. Hilmi`,
  `20. Ibnu`,
  `21. Luqman`,
  `22. Marco`,
  "23. Mis'al",
  `24. Rafi`,
  `25. Ramdhan`,
  `26. Sanca`,
  `27. Syahdin`,
  `28. Ripki`,
  `29. Risky`,
  `30. Tsabit`,
  `31. Usamah`,
  `32. Yoga`,
  `33. Yusuf`,
];

export const angkatan17 = [
  '\n1. Abdul.K',
  '2. Abdillah',
  '3. A.Syafiq.H',
  '4. Amri.R',
  '5. A.Kahfi.W',
  '6. Bintang',
  '7. Fallah.I.H',
  '8. Harun.Al.J',
  '9. Hasbi.A.As',
  '10. Hudzaifah',
  '11. Ibrahim.S.D',
  '12. Iqbal.J',
  '13. L.Ramadhan',
  '14. Madhan.R',
  '15. M.Adib.A',
  '16. M.Irfan.A',
  '17. M.Nadhif',
  '18. M.Naufal.S',
  '19. N.Fajar.A.I',
  '20. Parhan.A.G',
  '21. Yusra.S',
];

export const angakatan15 = [
  '1. Jundi',
  '2. Ilyas',
  '3. Luqman',
  '4. Yusuf',
  '5. Mazlang',
  "6. Mus'ab",
  '7. Anamosa',
  '8. Zian',
];
